### ISSUE TITLE
Lets use Doctrine ORM to nabage DB communications

### ISSUE THREAD

**Issue by muspelheim** [pivovarchyk/guestbook#14]
https://www.doctrine-project.org/projects/orm.html

**Comment by pivovarchyk** [comment]
I stated to use doctrine ORM. I had a problem with a many-to-one association.

**Comment by muspelheim** [comment]
what problem do you have?

**Comment by pivovarchyk** [comment]
Не извлекаются связанные данные о пользователе. Отдельно все извлекается и добавляется.

**Comment by muspelheim** [comment]
какая-то ошибка или просто нет данных?
