### ISSUE TITLE
duplicate code should be moved

### ISSUE THREAD

**Issue by muspelheim** [pivovarchyk/guestbook#16]
У вас тут куча дублированного кода, необходимо перенести все в абстрактный класс, добавить еще 1 метод, который вернет вам результат отсюда: `$image = imagecreatefrompng($filename);` и использовать эту функцию вместо того чтобы копировать все классы полностью. 

https://github.com/pivovarchyk/guestbook/tree/master/app/guestbook/app/controllers/image

**Comment by muspelheim** [comment]
они там отличаются всего 1 строкой

**Comment by pivovarchyk** [comment]
Я тоже так думала. Собиралась подправить. В паттернах в примерах абстрактных классов нет ).

**Comment by muspelheim** [comment]
а это не паттерн, это просто хорошая практика, не иметь дублированного кода
