### ISSUE TITLE
Поясните назначение файлов  в папке

### ISSUE THREAD

**Issue by muspelheim** [pivovarchyk/guestbook#21]
`app/guestbook/app/controllers/uploadedfiles`

Это не контроллеры, не понятно что эти классы там делают, возможно стоит перенести

**Comment by pivovarchyk** [comment]
Классы осуществляют загрузку текстовых файлов и изображений. А также уменьшение изображений в соответствии с требованиями. Согласна, что им здесь не место. Пока не знаю куда их лучше перенести. Или создать сервис загрузки.

**Comment by muspelheim** [comment]
перенесите их в `app/guestbook/app/helpers` или `app/guestbook/app/services`
